version: '1.0.0'

services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.24.2
    container_name: geoserver
    ports:
      - "80:8080"
    environment:
      GEOSERVER_ADMIN_USERNAME: admin
      GEOSERVER_ADMIN_PASSWORD: tsi23lesboss
      SKIP_DEMO_DATA: "true"
      POSTGRES_USERNAME: postgres #A CHANGER 
      POSTGRES_PASSWORD: postgres #A CHANGER
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgis
      POSTGRES_DB: geoserver #A CHANGER
    networks:
      - geoserver-net