version: '3.9'

services:

  db_postgres:
    image: postgis/postgis:16-3.4
    restart: always
    # set shared memory limit
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example					# LOGIN
    networks:
      - database_net
    volumes:
      - ./init_postgres:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data:rw

  # for developpement only ! remove on production
  pgAdmin:
    image: dpage/pgadmin4:8.4
    networks:
      - database_net
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com		# LOGIN
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret		# LOGIN
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json:ro

networks:
  database_net:

volumes:
  postgres_data:
